image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./.init-workspace.sh

  # Ref: https://github.com/gitpod-io/gitpod/issues/1997
  - name: pre-commit workaround
    command: echo "export PIP_USER=false" >> ~/.bashrc && . ~/.bashrc

  - name: emojify terminal
    command: cat ./fun/emoji.bashrc >> ~/.bashrc && . ~/.bashrc
